modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"
[[mods]]
modId="openlightsqa"
version="1"
displayName="Open Lights QA (development only)"
[[mixins]]
config="openlightsqa.mixins.json"
